name: Notify Slack on Release

on:
  release:
    types: [published] # 릴리스가 publish 되었을 때만 실행
  workflow_dispatch:

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare changelog
        id: changelog
        run: |
          body="${{ github.event.release.body }}"
          safe_body=$(echo "${body:-No changelog provided.}" | jq -Rs .)
          echo "body=${safe_body}" >> $GITHUB_OUTPUT

      - name: Send Slack message
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            # {
            #   "text": ":tada: *${{ github.event.release.tag_name }}* 릴리스가 배포되었습니다!\n<${{ github.event.release.html_url }}|릴리스 보러가기>\n\n${{ steps.changelog.outputs.body }}"
            # }
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<https://myfranchise.kr|myfranchise.kr> v6.9.5\n"
                  }
                },
                {
                  "type": "rich_text",
                  "elements": [
                    {
                      "type": "rich_text_list",
                      "style": "bullet",
                      "indent": 0,
                      "elements": [
                        {
                          "type": "rich_text_section",
                          "elements": [
                            {
                              "type": "emoji",
                              "name": "${{ github.event.release.tag_name }}"
                            }
                          ]
                        },
                        {
                          "type": "rich_text_section",
                          "elements": [
                            {
                              "type": "text",
                              "text": "${{ github.event.release.html_url }}"
                            }
                          ]
                        },
                        {
                          "type": "rich_text_section",
                          "elements": [
                            {
                              "type": "link",
                              "url": "https://example.com/",
                              "text": "with a link",
                              "style": {
                                "bold": true
                              }
                            }
                          ]
                        },
                        {
                          "type": "rich_text_section",
                          "elements": [
                            {
                              "type": "text",
                              "text": "${{ steps.changelog.outputs.body }}"
                            }
                          ]
                        },
                        {
                          "type": "rich_text_section",
                          "elements": [
                            {
                              "type": "text",
                              "text": "this is the end"
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
