name: Notify Slack on Release

on:
  release:
    types: [published] # 릴리스가 publish 되었을 때만 실행
  workflow_dispatch:

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack message
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": ":tada: 새로운 릴리스가 배포되었습니다!\n*${{ github.event.release.name }}*\n<${{ github.event.release.html_url }}|릴리스 보러가기>\n\n```"${{ github.event.release.body }}"```"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
