name: Notify Slack on Release

on:
  release:
    types: [published] # 릴리스가 publish 되었을 때만 실행
  workflow_dispatch:

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare changelog
        id: changelog
        run: |
          body="${{ github.event.release.body }}"
          safe_body=$(echo "${body:-No changelog provided.}" | jq -Rs .)
          echo "body=${safe_body}" >> $GITHUB_OUTPUT

      - name: Send Slack message
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "pr review request" # 메시지의 본문을 설정합니다.
              "blocks": [ # 메시지의 블록을 설정합니다.
                {
                  "type": "section", # 블록의 타입을 설정합니다.
                  "text": { # 텍스트 타입의 블록을 설정합니다.
                    "type": "mrkdwn", # 텍스트의 마크다운 타입을 설정합니다.
                    "text": "리뷰어로 할당되었습니다.\\\\n • 제목: PR 제목\\n • 리뷰어: @리뷰어 \\n • 링크: 리뷰 링크" # 메시지의 내용을 설정합니다.
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
