name: Notify Slack on Release

on:
  release:
    types: [published] # 릴리스가 publish 되었을 때만 실행
  workflow_dispatch:

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare changelog
        id: changelog
        run: |
          body="${{ github.event.release.body }}"
          safe_body=$(echo "${body:-No changelog provided.}" | jq -Rs .)
          echo "body=${safe_body}" >> $GITHUB_OUTPUT

      - name: Send Slack message
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "channel": "#general",
              "text": "New Release: ${{ github.event.release.tag_name }}",
              "attachments": [
                {
                  "color": "#36a64f",
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "<https://myfranchise.kr|myfranchise.kr> v6.9.5\n"
                      }
                    },
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "${{ steps.changelog.outputs.body }}"
                      }
                    }
                  ]
                }
              ],
              "icon_emoji": ":robot_face:"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
